{
 "save": "/leonardo_scratch/large/userexternal/amohamed/Llama-2-7b-neox-eus-noeng_15112024",
 "load": "/leonardo_scratch/large/userexternal/amohamed/Llama-2-7b-neox-eus-noeng_15112024",
 "finetune": false
}