{
 "save": "/leonardo_scratch/large/userexternal/amohamed/Llama-2-7b-neox-eus-curriculum_first_500_steps",
 "load": "/leonardo_scratch/large/userexternal/amohamed/Llama-2-7b-neox-eus-curriculum_first_500_steps",
 "finetune": false
}