{
 "save": "/leonardo_scratch/large/userexternal/amohamed/Llama-2-7b-neox-eus-l2loss_29072024",
 "load": "/leonardo_scratch/large/userexternal/amohamed/Llama-2-7b-neox-eus-l2loss_29072024",
 "finetune": false
}