{
 "save": "/leonardo_scratch/large/userexternal/amohamed/Llama-2-13b-neox-eus-v1.1-noeng",
 "load": "/leonardo_scratch/large/userexternal/amohamed/Llama-2-13b-neox-eus-v1.1-noeng",
 "finetune": false
}