{
 "save": "/leonardo_scratch/large/userexternal/amohamed/Llama-2-7b-neox-arabic-english-curr",
 "load": "/leonardo_scratch/large/userexternal/amohamed/Llama-2-7b-neox-arabic-english-curr",
 "finetune": false
}