{
 "save": "/leonardo_scratch/large/userexternal/amohamed/Llama-2-7b-neox-eus-latxa-7b-v1.1_eng_first500step_cntdx",
 "load": "/leonardo_scratch/large/userexternal/amohamed/Llama-2-7b-neox-TP-1",
 "finetune": true
}