{
  "pipe_parallel_size": 0,
  "model_parallel_size": 1,

  "optimizer": {
     "type": "Adam",
     "params": {
       "lr": 0.0001,
       "max_grad_norm": 1.0,
       "betas": [0.9, 0.95]
     }
   },
  
  "train_micro_batch_size_per_gpu": 8,
  "gradient_accumulation_steps": 1,

  "gradient_clipping": 1.0,
  "weight_decay": 0.1,
  "hidden_dropout": 0,
  "attention_dropout": 0,

  "train_iters": 10000,
  "lr_decay_iters": 10000,
  "lr_decay_style": "cosine",
  "min_lr": 0.0000033,
  "warmup": 0.1,

  #"wandb_run_name": "latxa_eng_13072024",
}
